INSERT INTO `baballergens` (`group`, `name`, `number`, `protease`) VALUES
(‘A - Trees', 'Pine Mix', 2204, 'Low'),
('A - Trees', 'Oak Mix', 2306, 'Low'),
('A - Trees', 'Red Alder', 1019, 'Low'),
('A - Trees', 'Birch Mix', 1169, 'Low'),
('A - Trees', 'Hackberry', 1664, 'Low'),
('A - Trees', 'Black Willow', 2678, 'Low'),
('A - Trees', 'Common Cottonwood', 1436, 'Low'),
('A - Trees', 'White Ash', 1061, 'Low'),
('A - Trees', 'American Sycamore', 2564, 'Low'),
('A - Trees', 'Mulberry Mix (RW)', 1910, 'Low'),
('B - Trees', 'Shagbark Hickory', 1703, 'Low'),
('B - Trees', 'Black Walnut', 2627, 'Low'),
('B - Trees', 'Boxelder/Maple Mix (BHR)', 1214, 'Low'),
('B - Trees', 'American Elm', 1541, 'Low'),
('B - Trees', 'Red Cedar', 1340, 'Low'),
('B - Trees', 'Pecan Tree', 2099, 'Low'),
('B - Trees', 'Olive Tree', 2051, 'Low'),
('B - Trees', 'Bald Cypress', 1454, 'Low'),
('B - Trees', 'Hard/Sugar Maple', 1832, 'Low'),
('B - Trees', 'Sweet Gum', 1661, 'Low'),
('C - Grass', 'Bermuda Grass', 537, 'Low'),
('C - Grass', 'Johnson Grass', 1745, 'Low'),
('C - Grass', 'Kentucky Bluegrass (Standardized)', 545, 'Low'),
('C - Grass', 'Orchard Grass (Standardized)', 718, 'Low'),
('C - Grass', 'Perrenial Ryegrass (Standardized)', NULL, 'Low'),
('C - Grass', 'Meadow Fescue (Standardized)', 611, 'Low'),
('C - Grass', 'Timothy (Standardized)', 831, 'Low'),
('C - Grass', 'Sweet Vernalgrass (Standardized)', 825, 'Low'),
('C - Grass', 'Redtop (Standardized)', 777, 'Low'),
('C - Grass', 'Bahia Grass', 1082, 'Low'),
('D - Weeds', 'Marshelder/Poverty Weed Mix (BPT)', 1859, 'Low'),
('D - Weeds', 'Mugwort Sagebrush', 2414, 'Low'),
('D - Weeds', 'Dock/Sorrel Mix(DS)', 1517, 'Low'),
('D - Weeds', 'Careless/Pigweed (CR)', 1301, 'Low'),
('D - Weeds', 'Ragweed Mix (GSW)', 2318, ''),
('D - Weeds', 'English Plantain', 2213, 'Low'),
('D - Weeds', 'Eastern Dog Fennel', 2058, 'Low'),
('D - Weeds', 'Lambs Quarters', 1787, 'Low'),
('D - Weeds', 'Nettle', 1946, 'Low'),
('D - Weeds', 'Common Cockelbur', 1406, 'Low'),
('E - Animal', 'Dog Hair and Dander (4825)', 4825, 'Low'),
('E - Animal', 'Dog Hair and Dander (4084)', 4084, 'Low'),
('E - Animal', 'Guinea Pig Hair and Dander', 4402, 'Low'),
('E - Animal', 'AP Cat Hair (Standardized)', 4815, 'Low'),
('E - Animal', 'BLANK', NULL, 'Low'),
('E - Animal', 'Feather Mix', 4350, 'Low'),
('E - Animal', 'AP Cattle Hair and Dander', 4812, 'Low'),
('E - Animal', 'AP Horse Hair and Dander', 4856, 'Low'),
('E - Animal', 'Standardized Mite, Dermatophagoides pteronyssinus', 6692, 'High'),
('E - Animal', 'Standardized Mite, Dermatophagoides farinae', 6720, 'High'),
('F - Environmental', 'Alternaria Tenuis (Alternaria alternata)', 5009, 'High'),
('F - Environmental', 'Aspergillus Fumigatus', 5021, 'High'),
('F - Environmental', 'Hormodendrum Cladosporioides (Cladosporium cladosporioides)', 5129, 'High'),
('F - Environmental', 'Helminthosporium Interseminatum (Dendryphiella vinosa)', 5125, 'High'),
('F - Environmental', 'Penicillium Mix', 5169, 'High'),
('F - Environmental', 'Epicoccum Nigrum', 5101, 'High'),
('F - Environmental', 'Botrytis cinerea', 5049, 'High'),
('F - Environmental', 'Cockroach Mix', 6585, 'High'),
('F - Environmental', 'Glycerin', 6806, NULL),
('F - Environmental', 'Histamine', 7099, NULL);
